### ISSUE TITLE
Tiny Tiny RSS v15.7 (ee4c460) can't enable

### ISSUE THREAD

**Issue by ptsa** [atallo/ttrss_fullpost#2]
Tiny Tiny RSS v15.7 (ee4c460) can't enable

plugins  can't find it

**Comment by atallo** [comment]
Can you provide more info? Like screen capture, or log

**Comment by ptsa** [comment]
![1112](https://cloud.githubusercontent.com/assets/4506307/11205176/909bc40a-8d40-11e5-8d8a-229c622e72cc.jpg)
![1113](https://cloud.githubusercontent.com/assets/4506307/11205180/9618bd20-8d40-11e5-83d2-152715601b7e.jpg)
no error log

**Comment by atallo** [comment]
Any info in Preferences -> System ?

**Comment by ptsa** [comment]
empty

**Comment by atallo** [comment]
Ok, thanks. I need install 15.7 (ee4c460) version. In some days I can find a solution. (Now you can use similar plugin af_readability  )

**Comment by atallo** [comment]
Fixet it https://github.com/atallo/ttrss_fullpost/commit/d84e06d99e75fb75c6b1a45ff7dca2cf65831c8b

Thanks! ptsa
